modules:
  - galsim.des
  - galsim_extra
  - montara
  - numpy

pipeline:
  steps: [stash_prep, coadd_nwgint]

stash_prep:
  desrun: "des-pizza-slices-y6-v12"
  imsim_data: "$os.environ['IMSIM_DATA']"
  bands: ["r", "i", "z"]
  tilename: DES2359-6539

coadd_nwgint:
  run_on_inputs: True
