modules:
  - galsim.des
  - galsim_extra
  - montara
  - numpy

pipeline:
  steps:
    - galsim_montara
    - true_detection
    - meds
    - newish_metacal

true_detection:
  box_size: 32

newish_metacal:
  bands: ['r']

meds:
  cutout_types:
    - image
    - weight
    - seg
    - bmask
  meds_dir: meds
  meds_run: y3v02
  sub_bkg: False
  delete_images: True
  add_psf_data: True
  use_joblib: True
  stage_output: True
  use_rejectlist: False

input: {}

image:
  type: WideScattered
  border: 15
  random_seed: 1234
  nproc: 1

  # The number of objects across the full focal plane.
  nobjects: 4

  #could read this from the image headers, but let's set them explicitly for now
  xsize: 2048
  ysize: 4096

psf:
  type: Gaussian
  fwhm: 0.9
  flux: 1.0

gal:
  type: Exponential
  half_light_radius: 0.5
  ellip:
    type: G1G2
    g1: 0.0
    g2: 0.0
  flux:
    type: Eval
    # Input catalog has mag
    # convert to flux via flux = 10**(0.4*(mag_zp-mag))
    str: "10**(0.4*(mag_zp-mag))"
    fmag: 17.

star:
  type: Gaussian  # Basically a delta function.
  sigma: 1.e-6
  flux: 1.0

stamp:
  type: MixedScene
  objects:
    # These give the probability of picking each kind of object.  The
    # choice of which one is picked for a given object is written to the
    # base dict as base['current_obj_type'] and is thus available as
    # @current_obj_type.  The actual constructed object is similarly
    # available as @current_obj.  And the type by number in this list
    # (starting with 0 for the first) is @current_obj_type_index.
    star: 0.0
    gal: 1.0
  obj_type: 'gal'
  draw_method: auto
  shear:
      type: G1G2
      g1: 0.02
      g2: 0.00
  gsparams:
      maximum_fft_size: 16384

output:
  type: DESTile
  nproc: 1
  bands: [r]
  desrun: y3v02
  noise_mode: from_weight
  add_bkg: False
  tilename: DES0000-5622
  grid_objects: True

  # save weight and badpix extensions too
  badpix:
      hdu: 1
  weight:
      hdu: 2

  truth:
    # DESTile type fills in filename
    columns:
      num: obj_num
      half_light_radius:
        type: Eval
        str: "0.0 if @current_obj_type=='star' else hlr"
        fhlr: "@gal.half_light_radius"
      g1: "$(@stamp.shear).g1"
      g2: "$(@stamp.shear).g2"
      obj_type: "@current_obj_type"
      obj_type_index: "@current_obj_type_index"
      band: "band"
      mag_zp: "$mag_zp"
