modules:
  - galsim.des
  - galsim_extra
  - montara
  - numpy
  - eastlake

pipeline:
  steps: [galsim_montara]

galsim_montara: {}

input:
  des_piff:
    file_name: "$piff_path"

image:
  type: WideScattered
  border: 15

  # The number of objects across the full focal plane.
  nobjects: 90000

  #could read this from the image headers, but let's set them explicitly for now
  xsize: 2048
  ysize: 4096

  world_pos:
    type: RADec
    type: RADec
    ra:
      type: Degrees
      theta: { type: Random, min: "$ra_min_deg", max: "$ra_max_deg" }
    dec:
      type: Radians
      theta:
        type: RandomDistribution
        function: "math.cos(x)"  # Uniform on the sky means P(delta) ~ cos(delta)
        x_min: "$numpy.radians(dec_min_deg)"
        x_max: "$numpy.radians(dec_max_deg)"

psf:
  type: DES_Piff
  depixelize: false
  gi_color: null
  iz_color: null

gal:
  type: Exponential
  half_light_radius: 0.5
  flux: "$10**(0.4*(mag_zp-18.0))"

star:
  type: Gaussian
  sigma: 1.e-6
  flux: 0

stamp:
  type: MixedScene
  objects:
    star: 0
    gal: 1
  draw_method: auto
  # shear_scene: False
  shear:
    type: G1G2
    g1: 0.00
    g2: -0.02
  gsparams:
    maximum_fft_size: 16384

output:
  type: DESTile
  n_se_test: 4
  # The number of exposures to build
  tilename: DES0433-2332
  bands: ['r']
  desrun: "des-pizza-slices-y6-v14"
  imsim_data: "$os.environ['IMSIM_DATA']"
  noise_mode: from_weight
  add_bkg: False
  grid_objects: True

  # Save weight and badpix extensions too
  badpixfromfits:
    hdu: 1
    mask_hdu: 2
    mask_file: "$orig_image_path"
  weight:
    hdu: 2

  truth:
    columns:
      num: obj_num
      g1: "$(@stamp.shear).g1"
      g2: "$(@stamp.shear).g2"
      band: "band"
      mag_zp: "$mag_zp"
